### ISSUE TITLE
Sub Expression Editing

### ISSUE THREAD

**Issue by neoaero99** [skuhl/RobotRun#233] opened 2017-07-28 17:37 UTC
There is an issue with how the options for operators is determined for sub expressions.

For example, I have a sub expression as the first element of a register expression. The first element in the sub expression is a data register operand, however, when I try to add an operator to the right of the data register operand, the only options I have are the logic operators (AND, OR, NOT).

**Comment by vtdrusch** [comment] 2017-07-31 02:05
Thus far, I haven't been able to reproduce this behavior. The only situation in which it should be possible to see just the logic operators is in the case where the previous operand or sub-expression evaluates to a boolean type operand, and only for IO type register expressions and IF statements. I may have done something to fix this inadvertently while probing the NOT operator issue, but I'll leave this open for now until we can test with your specific program to verify whether or not this has been fixed.

**Comment by vtdrusch** [comment] 2017-07-31 02:06
Also, there seems to be another issue with editing sub expressions related to the opEdit variable being incorrectly set, causing the wrong operand to be edited in some cases, or resulting in a null pointer error.

**Comment by vtdrusch** [comment] 2017-08-02 16:24
Expression editing appears to be working again, closing this issue for now.

**Closed as completed by vtdrusch** 2017-08-02 16:24 UTC
Labels: bug, high priority
