### ISSUE TITLE
Joint Interpolation Offsets

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#94] opened 2016-08-16 23:36 UTC
approach point one was recorded. when i try to move to the same point it does not move to same point but the tool frame is created successfully.

**Comment by neoaero99** [comment] 2016-08-17 19:56
So, I believe that the problem is that depending on the speed at which the Robot's moving. When it comes close enough to the destination point, it will stop just short of the point.

**Comment by neoaero99** [comment] 2016-08-19 19:57
For joint interpolation, the Robot should move to the target angles exactly (if possible), so I'll close this for now.

**Closed as completed by neoaero99** 2016-08-19 19:57 UTC
Labels: bug, low priority
