### ISSUE TITLE
Can Enter or Edit the first column in the PR[x, y] Register Statement Operand

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#119] opened 2016-09-11 22:42 UTC
![bug](https://cloud.githubusercontent.com/assets/17214301/18421095/591d2852-784f-11e6-83e2-ddca12dfa3f6.JPG)

**Comment by vtdrusch** [comment] 2016-09-24 18:17
Editing position registers as operands is now possible in register statements.

**Comment by neoaero99** [comment] 2016-09-24 22:49
I found a problem ...

You cannot confirm your input for the position register index, when using the P[x, y] option.

**Comment by neoaero99** [comment] 2016-09-24 22:52
More specifically, when you edit the second index, it prompts for both indices and works fine. However, when you try and edit the first index (which includes the 'P[' prefix), then the ENTER button does nothing.

**Comment by vtdrusch** [comment] 2016-09-24 22:54
I'm not seeing this behavior on my end, make sure you pull from the dev branch and try again.

**Comment by neoaero99** [comment] 2016-09-25 02:40
I pulled and you still cannot edit the first column ('P[x ') for a PR[x, y] operand.

**Comment by vtdrusch** [comment] 2016-09-25 19:17
I'm closing this issue again as I am unable to reproduce this bug. Check your code branch and try deleting any program saves. If you still have this problem, let me know exactly what you did to cause this bug, including your current screen, previous screen, and the full register statement you were trying to edit.

**Closed as completed by vtdrusch** 2016-09-25 19:17 UTC
Labels: bug, high priority
